In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

In [4]:
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [5]:
values

array([6, 1, 4, 4, 8])

In [6]:
big_array = np.random.randint(1, 100, size=100000)

In [7]:
%timeit compute_reciprocals(big_array)

115 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
def vectorized_recip(values):
    return 1.0 / values

In [9]:
%timeit vectorized_recip(big_array)

104 µs ± 287 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
x = np.arange(4)

In [11]:
x

array([0, 1, 2, 3])

In [12]:
x + 5

array([5, 6, 7, 8])

In [13]:
x - 5

array([-5, -4, -3, -2])

In [14]:
x / 5

array([0. , 0.2, 0.4, 0.6])

In [15]:
x // 5

array([0, 0, 0, 0])

In [16]:
x * 5

array([ 0,  5, 10, 15])

In [17]:
x % 5

array([0, 1, 2, 3])

In [18]:
x ** 5

array([  0,   1,  32, 243])

In [19]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [23]:
np.absolute(np.negative(np.power(np.add(np.multiply(0.5, x), 1), 2)))

array([1.  , 2.25, 4.  , 6.25])

In [24]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [25]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [26]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [27]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [28]:
np.arcsin(theta)

/tmp/ipykernel_47110/458218287.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(theta)


array([ 0., nan, nan])

In [29]:
np.arccos(theta)

/tmp/ipykernel_47110/3466450257.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(theta)


array([1.57079633,        nan,        nan])

In [30]:
np.arctan(theta)

array([0.        , 1.00388482, 1.26262726])

In [31]:
x = np.arange(1, 4)
x

array([1, 2, 3])

In [32]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [33]:
np.exp2(x)

array([2., 4., 8.])

In [34]:
np.power(3, x)

array([ 3,  9, 27])

In [36]:
np.power(2.0, x)

array([2., 4., 8.])

In [37]:
np.log(np.exp(x))

array([1., 2., 3.])

In [38]:
np.log10(np.power(10, x))

array([1., 2., 3.])

In [39]:
np.log10([10, 100, 1000, 1000000])

array([1., 2., 3., 6.])

In [40]:
np.tanh([1,0,-1])

array([ 0.76159416,  0.        , -0.76159416])