In [1]:
import numpy as np

In [3]:
arr_1d = np.random.random(5)
arr_1d

array([0.49981187, 0.93206395, 0.01393635, 0.60777219, 0.86168027])

In [4]:
arr_2d = np.random.random((5,3))
arr_2d

array([[0.1613666 , 0.51129462, 0.462699  ],
       [0.79621888, 0.33443403, 0.57410746],
       [0.50731425, 0.75694688, 0.55961918],
       [0.03921228, 0.49499332, 0.81355698],
       [0.81750817, 0.06922136, 0.41634693]])

In [5]:
np.random.seed(0)

In [6]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [7]:
x3.ndim

3

In [8]:
x3.shape

(3, 4, 5)

In [9]:
x3.size

60

In [10]:
x2.dtype

dtype('int64')

In [11]:
x3.nbytes

480

In [12]:
x3.itemsize * x3.size

480

In [13]:
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
x1[-2]

7

In [15]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [16]:
x2[1,1]

6

In [17]:
x2[2,0]

1

In [18]:
x2[2,2] = 9

In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 9, 7]])

In [20]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 9, 7]])

In [21]:
x2[1::1, 0]

array([7, 1])

In [22]:
x2[1::2, 0]

array([7])

In [23]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x1[:5]

array([5, 0, 3, 3, 7])

In [25]:
x1[5:]

array([9])

In [26]:
x1[::2]

array([5, 3, 7])

In [27]:
x1[1::2]

array([0, 3, 9])

In [28]:
x1

array([5, 0, 3, 3, 7, 9])

In [29]:
x1[:1:-2]

array([9, 3])

In [30]:
x1[6:1:-2]

array([9, 3])

In [32]:
# x1[6]

In [33]:
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
x1[::-1]

array([9, 7, 3, 3, 0, 5])

In [35]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 9, 7]])

In [36]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [37]:
x2[:3]

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 9, 7]])

In [38]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 9]])

In [39]:
x2[::-1]

array([[1, 6, 9, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [40]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 9, 7]])

In [41]:
x2[::-1, ::-1]

array([[7, 9, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 9, 7]])

In [43]:
x2[1]

array([7, 6, 8, 8])

In [44]:
x2[:, 2]

array([2, 8, 9])

In [45]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 9, 7]])

In [46]:
x2_sub = x2[:2, :2]
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 9, 7]])

In [47]:
x2_sub

array([[3, 5],
       [7, 6]])

In [48]:
x2_sub[0, 0] = 99
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  9,  7]])

In [49]:
x2_sub_copy = x2[:2, :2].copy()

In [50]:
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [51]:
x2_sub_copy[0, 0] = 45
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  9,  7]])

In [52]:
x2_sub

array([[99,  5],
       [ 7,  6]])

In [53]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
x = np.array([1,2,3])
x.ndim

1

In [55]:
x

array([1, 2, 3])

In [56]:
x_res1 = x.reshape((3,1))
x_res1

array([[1],
       [2],
       [3]])

In [57]:
x

array([1, 2, 3])

In [58]:
x_res2 = x.reshape((1, 3))
x_res2

array([[1, 2, 3]])

In [59]:
x_res3 = x[np.newaxis, :]
x_res4 = x[:, np.newaxis]
x_res3

array([[1, 2, 3]])

In [60]:
x_res4

array([[1],
       [2],
       [3]])

In [61]:
x 

array([1, 2, 3])

In [62]:
y = np.array([3,2,1])

In [63]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [64]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
grid_concat=np.concatenate([grid, grid])

In [66]:
grid.shape

(2, 3)

In [68]:
grid_concat.shape

(4, 3)

In [69]:
x.shape

(3,)

In [70]:
y.shape

(3,)

In [71]:
xy_concat = np.concatenate([x, y])
xy_concat.shape

(6,)

In [72]:
grid_sec = np.concatenate([grid, grid], axis=1)
grid_sec

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [73]:
grid_sec.shape

(2, 6)

In [74]:
x

array([1, 2, 3])

In [75]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
np.vstack([grid, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [79]:
# np.hstack([grid, x])

In [80]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [82]:
np.hstack([grid, x[:, np.newaxis]])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [84]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
x

array([1, 2, 3])

In [86]:
x_2 = x[:2]
x_2

array([1, 2])

In [87]:
np.hstack([grid, x_2[:, np.newaxis]])

array([[1, 2, 3, 1],
       [4, 5, 6, 2]])

In [88]:
x = np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [89]:
x1, x2, x3 = np.split(x, [3,5])

In [90]:
x1

array([1, 2, 3])

In [91]:
x2

array([99, 99])

In [92]:
x3

array([3, 2, 1])

In [93]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
upper, lower = np.vsplit(grid, [2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [95]:
upper2, lower2 = np.split(grid, [2])
upper2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
left, right = np.hsplit(grid, [2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])